---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


#Web scraping IMDB

```{r}
library(rvest)
library(dplyr)
```




```{r}
#link = "https://www.imdb.com/search/title/?genres=adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,"

get_cast = function(movie_link){
  movie_page = read_html(movie_link)
  movie_cast = movie_page %>% html_nodes(".primary_photo+ td a") %>%
    html_text()  %>% paste(collapse = ",")
  return(movie_cast)
  
  }

movies = data.frame()


for (page_result in seq(1, 101, 50)){
  link = paste0("https://www.imdb.com/search/title/?title_type=feature&num_votes=25000,&genres=adventure&sort=user_rating,desc&start=", page_result , "&ref_=adv_nxt")
  page = read_html(link)
  name = page %>% html_nodes(".lister-item-header a") %>% html_text()
movie_links = page %>% 
  html_nodes(".lister-item-header a") %>%
    html_attr("href") %>%
  paste("https://www.imdb.com", ., sep="") #We paste the imdb.com together with the link to the movie(that is without the imdb.com)
#movie links: instead of grabing the text, 
year = page %>% html_nodes(".text-muted.unbold") %>% html_text()
rating = page %>% html_nodes(".ratings-imdb-rating strong") %>% html_text()
synopsis = page %>% html_nodes(".ratings-bar+ .text-muted") %>% html_text()
cast = sapply(movie_links, FUN = get_cast, USE.NAMES = FALSE)

movies = rbind(movies, data.frame(name,year, rating, synopsis, cast, stringsAsFactors = FALSE))

print(paste("Page:", page_result))
}

#We are going to do a function that takes each of these movie links, and scrapes these movie members.


View(movies)



```

<br>

Make a dataframe

```{r}
movies = data.frame(name,year, rating, synopsis, cast, stringsAsFactors = FALSE)
View(movies)
```


Now, we are going to look at nested links, which is when you scrape links, and then you navigate to those links, and scrape from those links! Now we are not only on the frontage og the movies, but we have to go into each of the movies and scrape for the stars there. 



<br>
<br>

now we are going to make a for loop, that will go through throw all the pages:


```{r}



```





